server:
  port: 8082

spring:
  application:
    name: compras
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/
          tenant-id: 8ea291c8-4670-4598-8f0f-b5e216b5b755
          audience: c6445b4c-7863-42ac-a620-2fa3b5ea58d8

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:compras_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://3.213.91.126}
